use webctl_ir::{OperationKind, OperationTransport, SiteDescriptor};

pub fn emit_executor_config(descriptor: &SiteDescriptor) -> String {
    let site = &descriptor.meta.site_name;
    let display = &descriptor.meta.display_name;
    let source_url = &descriptor.meta.source_url;

    let mut tools = Vec::new();

    for op in &descriptor.operations {
        let cmd_name = op.command_path.join(".");
        let description = op.description.replace('"', "\\\"");
        let op_kind = match op.operation_kind {
            OperationKind::Read => "read",
            OperationKind::Write => "write",
            OperationKind::Other => "other",
        };

        let url = match &op.transport {
            OperationTransport::Http(http) => {
                if let Some(ref http_surface) = descriptor.http {
                    if let Some(endpoint) = http_surface.endpoints.get(http.endpoint_index) {
                        format!("{}{}", base_url(source_url), endpoint.path)
                    } else {
                        format!("{}/unknown", base_url(source_url))
                    }
                } else {
                    format!("{}/unknown", base_url(source_url))
                }
            }
            OperationTransport::Ax(_) => format!("ax://{site}/{cmd_name}"),
        };

        tools.push(format!(
            r#"      "{site}.{cmd_name}": {{
        description: "{description}",
        operationKind: "{op_kind}",
        execute: async () => {{
          const res = await fetch("{url}");
          return {{ status: res.status, body: await res.text() }};
        }},
      }}"#
        ));
    }

    let tools_str = tools.join(",\n");

    format!(
        r#"// Auto-generated by webctl emit just-bash
// Source: {source_url}
// Site: {site} ({display})
// Generated: {timestamp}
//
// Usage with just-bash:
//   import {{ executorConfig }} from "./{site}.config";
//   const bash = new Bash({{ executor: executorConfig }});
//   await bash.exec('{site} --help');

export const executorConfig = {{
  tools: {{
{tools_str}
  }},
  onToolApproval: async (request) => {{
    if (request.operationKind === "read") return {{ approved: true }};
    return {{ approved: false, reason: "write operations require explicit approval" }};
  }},
}};
"#,
        timestamp = chrono_placeholder(),
    )
}

fn base_url(source_url: &str) -> String {
    url::Url::parse(source_url)
        .map(|u| format!("{}://{}", u.scheme(), u.host_str().unwrap_or("localhost")))
        .unwrap_or_else(|_| source_url.to_string())
}

fn chrono_placeholder() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    format!("{secs}")
}
